# My Variables
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNzZlOTA4YjdmODE3N2Y2YWJiODNiNCIsImlhdCI6MTYwMTk2OTE2MiwiZXhwIjoxNjA0NTYxMTYyfQ.XsmBPZ3t4KruoM2OwkLkfCwrFMt1lPKgtTQVjdMd8us
### Get request (auth)
GET http://localhost:5000/api/products


### Get contact
GET http://localhost:5000/api/products/5f76e908b7f8177f6abb83b8


### Get userprofile
GET http://localhost:5000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNzZlOTA4YjdmODE3N2Y2YWJiODNiNCIsImlhdCI6MTYwMTk2OTE2MiwiZXhwIjoxNjA0NTYxMTYyfQ.XsmBPZ3t4KruoM2OwkLkfCwrFMt1lPKgtTQVjdMd8us



### Post Request
GET http://localhost:5000/api/auth

### Register User
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
   "email": "JohnDoe@example.com",
   "password": "123456"
}

### Register User
POST http://localhost:5000/api/users
Content-Type: application/json

{
   "name": "testuser",
   "email": "testuser@gmail.com",
   "password": "123456"
}


### Login User
POST http://localhost:5000/api/auth
Content-Type: application/json

{
   "email": "whatever@gmail.com",
   "password": "1234567"
}

